import { jsx, jsxs } from "react/jsx-runtime";
function TermsAndCondition() {
  return /* @__PURE__ */ jsx("div", { className: "w-full flex justify-center py-4", children: /* @__PURE__ */ jsxs("div", { className: "mt-10 md:w-[1250px]", children: [
    /* @__PURE__ */ jsx("h1", { className: "text-4xl font-bold", children: "Moving Papa Terms and Condition" }),
    /* @__PURE__ */ jsx("h2", { children: "Effective Date: 2025-04-26" }),
    /* @__PURE__ */ jsx("br", {}),
    /* @__PURE__ */ jsxs("div", { className: "", children: [
      /* @__PURE__ */ jsx("p", { className: "font-bold text-xl", children: "SMS Terms of Service" }),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "1. SMS Consent Communication:" }),
      "By opting into SMS from Moving Papa via web form, text message, or other medium, you are agreeing to receive SMS messages from Moving Papa. Your consent is not a condition of purchase, and you may opt out at any time.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "2. Types of SMS Communications:" }),
      "This includes SMS messages for: \u2022 Moving quotes and estimates",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Appointment scheduling and confirmations",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Appointment reminders",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Service updates and status notifications",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Order confirmations",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Delivery notifications",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Customer feedback requests",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Account notifications",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "3. Message Frequency:" }),
      "Message frequency varies based on your interaction with our services. You may receive several messages per week while actively using our services, and fewer messages during inactive periods.",
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "4. Potential Fees for SMS Messaging:" }),
      "Message and data rates may apply according to your wireless carrier plan. Moving Papa does not charge for text messages, but carrier message and data rates may apply.",
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "5. Opt-In Method:" }),
      "You can opt in to receive text messages by:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Checking the SMS consent box on our website forms",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Texting a designated keyword to our number",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Providing written consent through our paper forms",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Confirming consent through our double opt-in process",
      /* @__PURE__ */ jsx("br", {}),
      '\u2022 Verbal consent: When we ask you verbally, "Do you agree to receive Customer care text messages from Moving Papa. Reply STOP to opt-out; Reply HELP for support; Message & data rates may apply; Messaging frequency may vary. Visit movingpapa.com/vancouver/privacy-policy to see our privacy policy and movingpapa.com/vancouver/terms-and-condition for our Terms of Service." We will record and track your verbal consent by keeping a file in our CRM system.',
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "6. Opt-Out Method:" }),
      "To opt out at any time, text STOP to any message from us. Upon receipt of your STOP request, we will send one confirmation message and you will no longer receive SMS messages from Moving Papa.",
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "7. Help:" }),
      "For assistance with our SMS program, text HELP to any message from us or visit our website at https:/movingpapa.com/vancouver. You can also contact our support team directly using the contact information provided below.",
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "8. Standard Messaging Disclosures:" }),
      "Our SMS program is supported by most major carriers, including AT&T, Bell, Rogers, T-Mobile, Telus, Verizon, Virgin Mobile, and others. If you change your mobile phone number, you are responsible for notifying us to ensure you continue to receive our communications.",
      /* @__PURE__ */ jsx("br", {}),
      "For our privacy policy, visit movingpapa.com/vancouver/privacy-policy",
      /* @__PURE__ */ jsx("br", {}),
      "For our full Terms of Service, visit movingpapa.com/vancouver/terms-and-condition",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "Changes to Terms:" }),
      'Moving Papa reserves the right to modify these SMS Terms and Conditions at any time. We will notify you of any changes by posting the new Terms and Conditions on our website and updating the "Effective Date" above.',
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "Contact Us" }),
      "If you have questions regarding these SMS Terms and Conditions or Moving Papa's text messaging program, please contact us at:",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsxs("p", { className: "font-bold", children: [
        "Moving Papa - Vancouver",
        /* @__PURE__ */ jsx("br", {}),
        "33 Commercial Drive, Vancouver, BC V5L 0A2",
        /* @__PURE__ */ jsx("br", {}),
        "Email: Vancouver@movingpapa.com",
        /* @__PURE__ */ jsx("br", {}),
        "Phone: (604)-373-5582",
        /* @__PURE__ */ jsx("br", {})
      ] })
    ] })
  ] }) });
}
export {
  TermsAndCondition as default
};
