import { jsx, jsxs } from "react/jsx-runtime";
function PrivacyPolicy() {
  return /* @__PURE__ */ jsx("div", { className: "w-full flex justify-center py-4", children: /* @__PURE__ */ jsxs("div", { className: "mt-10 md:w-[1250px]", children: [
    /* @__PURE__ */ jsx("h1", { className: "text-4xl font-bold", children: "Moving Papa Privacy Policy" }),
    /* @__PURE__ */ jsx("h2", { children: "Effective Date: 2025-04-26" }),
    /* @__PURE__ */ jsx("br", {}),
    /* @__PURE__ */ jsxs("div", { className: "", children: [
      "At Moving Papa, your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, protect, and store your information when you interact with our services. We are committed to maintaining the confidentiality, integrity, and security of your personal information. This Policy applies to information collected through our website, emails, phone communications, online forms, customer service interactions, and any other method through which we engage with you.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "1. Information We Collect " }),
      "a. Information You Provide to Us ",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Personal Information: Name, email address, phone number, billing address, service addresses (origin and destination).",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Service Information: Details about your move (inventory lists, access details like elevators, parking information).",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Payment Information: Limited billing details necessary to process your transactions. Payment processing is securely handled by third-party providers.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Communications: Emails, calls, chat transcripts, and other communications with our customer support or sales team.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Feedback: Surveys, reviews, testimonials, and any other voluntary feedback you provide.",
      /* @__PURE__ */ jsx("br", {}),
      "b. Information We Collect Automatically",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Device Information: IP address, browser type, operating system, referring URLs.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Usage Data: Pages viewed, time spent on pages, navigation patterns, and interactions with the website.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Cookies and Tracking Technologies: We use cookies, pixels, and similar technologies to enhance website functionality, remember preferences, and understand usage trends.",
      /* @__PURE__ */ jsx("br", {}),
      "c. Information from Third Parties",
      /* @__PURE__ */ jsx("br", {}),
      "We may receive information about you from business partners, payment processors, advertising networks, or public sources to improve our services or for fraud prevention.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "2. How We Use Your Information" }),
      "We use your information to:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Provide, manage, and complete moving and truck rental services.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Communicate with you about your orders, service updates, and customer support requests.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Send administrative communications (e.g., booking confirmations, policy updates).",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Send promotional and marketing communications (you may opt-out at any time).",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Send SMS messages for appointment scheduling, order confirmations, and service updates.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Analyze website usage to improve our platform and customer experience.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Protect the rights, property, or safety of Moving Papa, our customers, or others.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022  Comply with legal and regulatory obligations.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "3. Legal Basis for Processing Personal Information" }),
      "If you are located in a jurisdiction that requires a legal basis for processing (such as the European Union under GDPR), we process your personal information based on the following legal grounds:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Performance of a contract: To provide moving services you requested.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Consent: For optional marketing communications and non-essential cookies.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Compliance with legal obligations: To meet regulatory requirements.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Legitimate interests: To improve services, ensure security, and protect against fraud.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "4. Sharing Your Information" }),
      "We may share your information with:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Service Providers: Companies that help us provide services (payment processors, dispatch software, background check providers, marketing service providers).",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Legal Compliance: When required by law, legal process, or government request.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Business Transfers: In case of a merger, sale, or acquisition, we may transfer information to the new business entity.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 With Your Consent: If you explicitly agree to sharing for specific purposes.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 SMS opt-in consent and phone numbers for the purpose of SMS are not being shared with any third parties under any circumstances. We do not sell or rent your personal information to third parties.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "5. Data Security" }),
      "We take reasonable and appropriate security measures to protect your personal information from loss, misuse, unauthorized access, disclosure, alteration, and destruction.",
      /* @__PURE__ */ jsx("br", {}),
      "These measures include:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 SSL encryption for data transmitted online.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Restricted access to personal data only to employees or service providers who need it.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Regular security reviews of our systems and processes.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 However, no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to protect your information, we cannot guarantee absolute security.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "6. Data Retention" }),
      "We retain your personal information:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 For as long as needed to provide services.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 As required by legal, tax, accounting, or regulatory obligations.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 To resolve disputes or enforce our agreements.",
      /* @__PURE__ */ jsx("br", {}),
      "When we no longer need your information, we securely destroy or de-identify it.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "7. Your Rights and Choices" }),
      "Depending on your jurisdiction, you may have the following rights regarding your personal information:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Access: Request access to the personal information we hold about you.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Correction: Request corrections to your personal information if inaccurate.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Deletion: Request deletion of your information, subject to legal requirements.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Objection: Object to certain processing (e.g., direct marketing).",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Withdraw Consent: Where processing is based on consent, you can withdraw it at any time.",
      /* @__PURE__ */ jsx("br", {}),
      "To exercise your rights, please contact us using the details provided below.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "8. Cookies and Similar Technologies" }),
      "We use cookies and similar technologies to:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Remember your preferences.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Analyze site traffic and trends.",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Offer better, faster, and safer browsing experiences.",
      /* @__PURE__ */ jsx("br", {}),
      "You can control cookie preferences through your browser settings. Disabling cookies may affect your user experience.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "9. International Transfers" }),
      "If you are located outside of Canada, your information may be transferred to, stored, and processed in Canada, where our servers and service providers are located. We take measures to ensure that any such transfers comply with applicable data protection laws.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "10. Children's Privacy" }),
      "Moving Papa does not knowingly collect personal information from children under the age of 13. If we learn that we have collected such information without parental consent, we will take steps to delete it.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "11. Third-Party Links" }),
      "Our website may contain links to third-party websites. This Privacy Policy does not apply to the practices of those websites. We encourage you to review the privacy policies of any third-party sites you visit.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "12. SMS Communications" }),
      "By providing your mobile phone number and opting into SMS communications, you consent to receive text messages from Moving Papa. These messages may include:",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Appointment confirmations and reminders",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Order updates and status notifications",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Service announcements",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Payment confirmations",
      /* @__PURE__ */ jsx("br", {}),
      "\u2022 Customer service communications",
      /* @__PURE__ */ jsx("br", {}),
      "Message frequency may vary. Message and data rates may apply. To opt out at any time, text STOP to the number from which you received the text. For help or support, text HELP or contact us using the information below.",
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "13. Changes to This Privacy Policy" }),
      'We may update this Privacy Policy from time to time. When we make changes, we will revise the "Effective Date" at the top of this page. If changes are significant, we may provide additional notice through our website or other means.',
      /* @__PURE__ */ jsx("br", {}),
      "We encourage you to review this Policy periodically to stay informed about how we are protecting your information.",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsx("p", { className: "font-bold", children: "Contact Us" }),
      "If you have any questions, concerns, or requests regarding your privacy or this Policy, you can reach us at:",
      /* @__PURE__ */ jsx("br", {}),
      /* @__PURE__ */ jsxs("p", { className: "font-bold", children: [
        "Moving Papa ",
        /* @__PURE__ */ jsx("br", {}),
        "200 Fairbank Ave, York, ON M6B 1G1",
        /* @__PURE__ */ jsx("br", {}),
        "Email: hello@movingpapa.com",
        /* @__PURE__ */ jsx("br", {}),
        "Phone:  (647) 251-8188",
        /* @__PURE__ */ jsx("br", {})
      ] })
    ] })
  ] }) });
}
export {
  PrivacyPolicy as default
};
